---
title: "Projet"
output: 
  html_document:
    code_folding: hide
    code_download: true
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
date: "`r format(Sys.Date(), '%d %B, %Y')`"
author:
   - name: ""
     affiliation: "Université de Bordeaux - CMI ISI M1 - UE : Projet de statistique pour données environnementales 2024"
---
title: "Projet oiseaux"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Sites <- read.csv("Data/BiodiverCite_sites.csv", header = TRUE, sep = ";")
Land_cartoISea <- read.csv("Data/LandUsePer_BM_2023_cartoISea.csv", header = TRUE)
Oiseaux <- read.csv("Data/Oiseaux_up_to_2023.csv", header = TRUE, sep = "\t")
```

```{r}
head(Sites)
```

```{r}
head(Land_cartoISea)
```

```{r}
head(Oiseaux)
```

```{r}
Oiseaux$Nom_Latin <- sapply(strsplit(Oiseaux$Nom_Taxon_Cite, "\\|"), function(x) trimws(x[1]))
Oiseaux$Year <- sapply(strsplit(Oiseaux$Date, "\\-"), function(x) trimws(x[1]))
print(Oiseaux)
```

```{r}
donnees_agregate <- aggregate(Denombrement_min ~ Temperature, data = Oiseaux, FUN = sum)

# Tracer le graphique
plot(donnees_agregate$Temperature, donnees_agregate$Denombrement_min, type = "b", 
     xlab = "Température (°C)", ylab = "Nombre d'oiseaux",
     main = "Nombre d'oiseaux par température",
     col = "blue", pch = 19)

```


```{r}
library(dplyr)
library(sp)
library(leaflet)
```

# Carte points 
```{r}
lambert_data <- data.frame(X =Land_cartoISea$X, Y = Land_cartoISea$Y)
coordinates(lambert_data) <- c("X", "Y")

proj4string(lambert_data) <- CRS("+proj=lcc +lat_1=48 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs")


wgs84 <- CRS("+proj=longlat +datum=WGS84")

lambert_to_wgs84 <- spTransform(lambert_data, wgs84)

lambert_to_wgs84
countryPolygons.df <- as.data.frame(lambert_to_wgs84)
countryPolygons.df
```

```{r}
leaflet(data = Land_cartoISea) %>% addTiles() %>%
  addMarkers(~countryPolygons.df$coords.x1, ~countryPolygons.df$coords.x2, )
```


###DOUNIA
```{r}


```


###SUHAILA
```{r}


```

###MATHILDE
```{r}


```

###KARINA
```{r}


```

